### ISSUE TITLE
Not working on El Capitan?

### ISSUE THREAD

**Issue by jaksz** [stephencelis/syn#6]
Hi, this is what I am getting:

<img width="452" alt="2015-08-20 5 43 29" src="https://cloud.githubusercontent.com/assets/13822469/9375245/9bb90f10-46fe-11e5-9f26-cb44fd627c39.png">

Is it possible that this is not working on El Capitan? Or is the problem somewhere else?

**Comment by stephencelis** [comment]
Should be fixed with v0.2.2, thanks!

**Comment by jaksz** [comment]
Thank you, but it seems that I cannot get v0.2.2 to install by using the pre-compiled version. I'm using the download script available in the `README` file but `syn -v` keeps outputting v0.2.1. Unfortunately I don't have `xcode` installed to compile it myself. Could you have a look at what is wrong? I think the source code is fine now, but the pre-compiled version hasn't been updated.
